WIP: get os infro
logtracing/python-pkg pull request #16
Opened 2023-06-13 17:07 UTC by renebarrera1022

2023-06-27 22:33 UTC, Th3Kr4t3 requested changes

2023-06-27 22:33 UTC, Th3Kr4t3 commented on src/logtracing/Logger.py
>      def flow(self):
Would you consider add this type of return?
```suggestion
    def flow(self) -> str:
```

2023-06-27 22:33 UTC, Th3Kr4t3 commented on src/logtracing/Logger.py
> +        if not isinstance(extra, dict) and not isinstance(extra, str):
It could be more compact as:
```suggestion
        if not isinstance(extra, (dict, str)):
```

2023-06-27 22:33 UTC, Th3Kr4t3 commented on src/logtracing/Logger.py
> +            raise Exception('extra must be dict or str')
We could be more specific with exception types like this (and line 32 & 15):
```suggestion
            raise ValueError('extra must be a dictionary or a string')
```

2023-06-28 20:59 UTC, vcgtz commented on src/logtracing/Logger.py
>      def flow(self):
@renebarrera1022 Can you look at this? After that, of changes are needed or not, pls close the comment.

2023-07-03 16:34 UTC, renebarrera1022 commented on src/logtracing/Logger.py
>      def flow(self):
Changed it. Thank you!

2023-07-03 16:38 UTC, renebarrera1022 commented on src/logtracing/Logger.py
> +            raise Exception('extra must be dict or str')
I changed the exception type, regarding the error message I like `dict` and `str` because they are the exact values returned by Python, but thank you for your suggestion

2023-07-03 16:43 UTC, renebarrera1022 commented on src/logtracing/Logger.py
> +        if not isinstance(extra, dict) and not isinstance(extra, str):
I changed it, thank you!

2023-07-03 17:17 UTC, vcgtz approved these changes

2023-07-03 17:17 UTC, merged